-- +goose Up
-- +goose StatementBegin

-- Semeia a Faixa de normalidade dos 55 Indicadores do catalogo (ADR 0015).
--
-- Cada linha cita a fonte, que e obrigatoria: sem fonte a faixa nao entra.
-- A pesquisa completa, com URL por linha e as divergencias entre sociedades
-- medicas, esta em docs/faixas/*.md, revisada antes desta migracao.
--
-- Regras que valeram na selecao das linhas, e nao sao obvias lendo o SQL:
--
-- 1. Uma linha por (Indicador, sexo, faixa de idade). Semear todas as linhas
--    pesquisadas quebraria a resolucao: vitamina D tinha tres posicoes e TSH
--    tinha faixas academicas cobrindo as mesmas idades das comerciais, todas
--    com a mesma especificidade, o que daria empate permanente e nenhuma
--    banda desenhada. A posicao brasileira foi semeada e as divergencias
--    ficaram registradas no proprio texto da linha.
-- 2. min ou max nulo significa faixa de um lado so, ou nenhum: HDL tem piso
--    sem teto, glicemia tem teto sem piso, LDL nao tem nenhum dos dois
--    porque a meta e definida por risco cardiovascular, que e estratificacao
--    medica e nao dado deste sistema.
-- 3. Marcador tumoral (CEA, CA 19-9) e PSA livre nao tem faixa de
--    normalidade: o que existe e limite de ensaio, e ele fica no texto,
--    nunca em min/max, para a tela nao desenhar banda que finge ser normal.
-- 4. Lacuna conhecida de 18 a 19 anos em TSH e nos lipidios da SBC, cujas
--    fontes comecam a faixa adulta em 20 anos. Nessa idade a tela diz
--    "nao cadastrada", que e a verdade.
-- 5. psa_total existe so para sexo M: aplica-se a quem tem prostata.

INSERT INTO indicator_normal_ranges
    (id, indicator_id, sex, age_min, age_max, min, max, text, source)
VALUES
    ('a2000000-0000-4000-8000-000000000001', (SELECT id FROM health_indicators WHERE code = 'glucose_serum'), NULL, NULL, NULL, NULL, 99, 'Glicemia de jejum (8h de jejum) normal: inferior a 100 mg/dL. Estratificação SBD/ADA: normal <100 mg/dL; pré-diabetes 100–125 mg/dL; diabetes ≥126 mg/dL (confirmar com 2ª dosagem se assintomático). Esta linha registra apenas a faixa NORMAL; min ficou vazio porque hipoglicemia não tem piso fixo consensual fora de contexto clínico.', 'Sociedade Brasileira de Diabetes — Diagnóstico de Diabetes Mellitus, https://diretriz.diabetes.org.br/diagnostico-de-diabetes-mellitus/'),
    ('a2000000-0000-4000-8000-000000000002', (SELECT id FROM health_indicators WHERE code = 'insulin_serum'), NULL, NULL, NULL, 2.6, 24.9, 'Insulina de jejum (8–12h), método imunoensaio (ECLIA). Faixa de referência do fabricante/laboratório; população geral adulta, sem estratificação por sexo ou idade divulgada.', 'Mayo Clinic Laboratories — Test 8664 (Insulin), https://www.mayocliniclabs.com/test-catalog/overview/8664'),
    ('a2000000-0000-4000-8000-000000000003', (SELECT id FROM health_indicators WHERE code = 'homa_ir'), NULL, NULL, NULL, NULL, NULL, 'Não há ponto de corte único consensual para HOMA-IR. O valor mais citado na literatura brasileira, do estudo BRAMS (Geloneze et al., população miscigenada), é >2,71 para HOMA1-IR (calculado com insulina em µU/mL e glicose em mg/dL, sem fator de correção) como sugestivo de resistência insulínica — mas é um ponto de corte de pesquisa epidemiológica, não uma "faixa de normalidade" laboratorial, e o próprio ELSA-Brasil encontrou valor ótimo diferente (2,35) variando por IMC. Por não haver consenso citável de faixa normal, min/max ficam vazios; a interpretação de resistência insulínica cabe ao médico.', 'Geloneze B, et al. Arq Bras Endocrinol Metab / BRAMS Study — resumo em https://www.scielo.br/j/abem/a/Fb4KV8mksGnjn9LzfQtQRqR/abstract/?lang=pt ; PubMed https://pubmed.ncbi.nlm.nih.gov/16310881/'),
    ('a2000000-0000-4000-8000-000000000004', (SELECT id FROM health_indicators WHERE code = 'hba1c'), NULL, NULL, NULL, NULL, 5.6, 'Faixa de normalidade (ausência de diabetes): abaixo de 5,7%. Pré-diabetes: 5,7%–6,4%. Diabetes: ≥6,5%. Esta linha traz a faixa de NORMALIDADE (usamos 5,6% como teto por ser o maior valor ainda "normal" em incrementos de 0,1%, já que o corte de pré-diabetes começa em 5,7%). ATENÇÃO: para quem já tem diagnóstico de diabetes, a meta terapêutica de HbA1c é outra coisa — em geral <7,0% na maioria dos adultos, individualizada pelo médico conforme risco de hipoglicemia, comorbidades e expectativa de vida — NÃO é a mesma faixa desta linha.', 'Sociedade Brasileira de Diabetes — Diagnóstico de Diabetes Mellitus, https://diretriz.diabetes.org.br/diagnostico-de-diabetes-mellitus/'),
    ('a2000000-0000-4000-8000-000000000005', (SELECT id FROM health_indicators WHERE code = 'estimated_average_glucose'), NULL, NULL, NULL, 68.1, 114.0, 'A glicemia média estimada (eAG) NÃO é medida diretamente: é calculada a partir da HbA1c pela fórmula do estudo ADAG, adotada pela ADA: eAG (mg/dL) = 28,7 × HbA1c(%) − 46,7. Faixa aqui derivada aplicando a fórmula aos limites da faixa normal de HbA1c (4,0% a 5,6%, considerando 4,0% como piso fisiológico usual de referência laboratorial e 5,6% como teto da normalidade — ver linha hba1c): 28,7×4,0−46,7=68,1 mg/dL; 28,7×5,6−46,7=114,0 mg/dL. Resultado deve ser lido como estimativa, não como medição direta.', 'American Diabetes Association — eAG/A1C Conversion Calculator, https://professional.diabetes.org/glucose_calc'),
    ('a2000000-0000-4000-8000-000000000006', (SELECT id FROM health_indicators WHERE code = 'erythrocytes'), 'M', NULL, NULL, 4.32, 5.67, 'Contagem de eritrócitos (hemácias), população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000007', (SELECT id FROM health_indicators WHERE code = 'erythrocytes'), 'F', NULL, NULL, 3.83, 4.99, 'Contagem de eritrócitos (hemácias), população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000008', (SELECT id FROM health_indicators WHERE code = 'hemoglobin'), 'M', NULL, NULL, 13.3, 16.5, 'Hemoglobina, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000009', (SELECT id FROM health_indicators WHERE code = 'hemoglobin'), 'F', NULL, NULL, 11.7, 14.9, 'Hemoglobina, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000010', (SELECT id FROM health_indicators WHERE code = 'hematocrit'), 'M', NULL, NULL, 39.2, 49.0, 'Hematócrito, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000011', (SELECT id FROM health_indicators WHERE code = 'hematocrit'), 'F', NULL, NULL, 35.1, 44.1, 'Hematócrito, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000012', (SELECT id FROM health_indicators WHERE code = 'mch'), NULL, NULL, NULL, 27.7, 32.7, 'Hemoglobina corpuscular média (HCM). A fonte publica o mesmo intervalo para homens e mulheres adultos, por isso não há linha separada por sexo.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000013', (SELECT id FROM health_indicators WHERE code = 'mcv'), 'M', NULL, NULL, 81.7, 95.3, 'Volume corpuscular médio (VCM), população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000014', (SELECT id FROM health_indicators WHERE code = 'mcv'), 'F', NULL, NULL, 83.1, 96.8, 'Volume corpuscular médio (VCM), população adulta brasileira saudável.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000015', (SELECT id FROM health_indicators WHERE code = 'mchc'), 'M', NULL, NULL, 32.4, 36.0, 'Concentração de hemoglobina corpuscular média (CHCM).', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000016', (SELECT id FROM health_indicators WHERE code = 'mchc'), 'F', NULL, NULL, 32.0, 35.2, 'Concentração de hemoglobina corpuscular média (CHCM).', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000017', (SELECT id FROM health_indicators WHERE code = 'rdw'), NULL, NULL, NULL, 11.8, 14.2, 'RDW (amplitude de distribuição dos eritrócitos). A fonte publica 11,8–14,1% para homens e 11,8–14,2% para mulheres adultos — diferença de apenas 0,1 ponto no limite superior; adotado o intervalo consolidado (mais amplo) numa única linha, sem distinção de sexo.', 'Fleury, Manual de Exames — Eritrograma, sangue total, https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000018', (SELECT id FROM health_indicators WHERE code = 'red_cell_morphology'), NULL, NULL, NULL, NULL, NULL, 'Resultado textual (avaliação microscópica do esfregaço sanguíneo). Não há faixa numérica: o resultado esperado em adulto saudável é a ausência de alterações morfológicas dignas de nota na série vermelha (sem anisocitose, poiquilocitose, hipocromia ou inclusões significativas). Qualquer achado é descrito em texto livre pelo laboratório.', 'Fleury, Manual de Exames — Eritrograma, sangue total (exame inclui avaliação morfológica da série vermelha), https://www.fleury.com.br/medicos/exames/eritrograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000019', (SELECT id FROM health_indicators WHERE code = 'leukocytes'), 'M', NULL, NULL, 3650, 8120, 'Contagem total de leucócitos, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000020', (SELECT id FROM health_indicators WHERE code = 'leukocytes'), 'F', NULL, NULL, 3470, 8290, 'Contagem total de leucócitos, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000021', (SELECT id FROM health_indicators WHERE code = 'neutrophils_abs'), 'M', NULL, NULL, 1590, 4770, 'Neutrófilos, valor absoluto (segmentados; bastonetes contam à parte, com valor de referência "até" um teto, sem faixa própria neste manual).', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000022', (SELECT id FROM health_indicators WHERE code = 'neutrophils_abs'), 'F', NULL, NULL, 1526, 5020, 'Neutrófilos, valor absoluto (segmentados; bastonetes contam à parte, com valor de referência "até" um teto, sem faixa própria neste manual).', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000023', (SELECT id FROM health_indicators WHERE code = 'neutrophils_pct'), NULL, NULL, NULL, NULL, NULL, 'Não foi encontrada, nas fontes qualificadas consultadas (Fleury, Manual de Exames), uma faixa de referência percentual estabelecida para neutrófilos em adultos — o laboratório publica apenas o valor absoluto (/mm3), por considerar essa a medida clinicamente validada.', 'Sem fonte citável para o percentual: o Fleury, Manual de Exames — Leucograma, sangue total (https://www.fleury.com.br/medicos/exames/leucograma-sangue-total) publica deliberadamente apenas o valor absoluto em /mm3, e a SBPC/ML não fixa tabela nacional. O Indicador absoluto correspondente tem faixa.'),
    ('a2000000-0000-4000-8000-000000000024', (SELECT id FROM health_indicators WHERE code = 'eosinophils_abs'), 'M', NULL, NULL, 34, 420, 'Eosinófilos, valor absoluto, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000025', (SELECT id FROM health_indicators WHERE code = 'eosinophils_abs'), 'F', NULL, NULL, 20, 340, 'Eosinófilos, valor absoluto, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000026', (SELECT id FROM health_indicators WHERE code = 'eosinophils_pct'), NULL, NULL, NULL, NULL, NULL, 'Não foi encontrada faixa percentual estabelecida em fonte qualificada; o laboratório publica apenas o valor absoluto (/mm3).', 'Sem fonte citável para o percentual: o Fleury, Manual de Exames — Leucograma, sangue total (https://www.fleury.com.br/medicos/exames/leucograma-sangue-total) publica deliberadamente apenas o valor absoluto em /mm3, e a SBPC/ML não fixa tabela nacional. O Indicador absoluto correspondente tem faixa.'),
    ('a2000000-0000-4000-8000-000000000027', (SELECT id FROM health_indicators WHERE code = 'basophils_abs'), NULL, NULL, NULL, 10, 80, 'Basófilos, valor absoluto. A fonte publica o mesmo intervalo para homens e mulheres adultos.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000028', (SELECT id FROM health_indicators WHERE code = 'basophils_pct'), NULL, NULL, NULL, NULL, NULL, 'Não foi encontrada faixa percentual estabelecida em fonte qualificada; o laboratório publica apenas o valor absoluto (/mm3).', 'Sem fonte citável para o percentual: o Fleury, Manual de Exames — Leucograma, sangue total (https://www.fleury.com.br/medicos/exames/leucograma-sangue-total) publica deliberadamente apenas o valor absoluto em /mm3, e a SBPC/ML não fixa tabela nacional. O Indicador absoluto correspondente tem faixa.'),
    ('a2000000-0000-4000-8000-000000000029', (SELECT id FROM health_indicators WHERE code = 'lymphocytes_abs'), 'M', NULL, NULL, 1120, 2950, 'Linfócitos, valor absoluto, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000030', (SELECT id FROM health_indicators WHERE code = 'lymphocytes_abs'), 'F', NULL, NULL, 1097, 2980, 'Linfócitos, valor absoluto, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000031', (SELECT id FROM health_indicators WHERE code = 'lymphocytes_pct'), NULL, NULL, NULL, NULL, NULL, 'Não foi encontrada faixa percentual estabelecida em fonte qualificada; o laboratório publica apenas o valor absoluto (/mm3).', 'Sem fonte citável para o percentual: o Fleury, Manual de Exames — Leucograma, sangue total (https://www.fleury.com.br/medicos/exames/leucograma-sangue-total) publica deliberadamente apenas o valor absoluto em /mm3, e a SBPC/ML não fixa tabela nacional. O Indicador absoluto correspondente tem faixa.'),
    ('a2000000-0000-4000-8000-000000000032', (SELECT id FROM health_indicators WHERE code = 'monocytes_abs'), 'M', NULL, NULL, 260, 730, 'Monócitos, valor absoluto, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000033', (SELECT id FROM health_indicators WHERE code = 'monocytes_abs'), 'F', NULL, NULL, 220, 650, 'Monócitos, valor absoluto, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Leucograma, sangue total, https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000034', (SELECT id FROM health_indicators WHERE code = 'monocytes_pct'), NULL, NULL, NULL, NULL, NULL, 'Não foi encontrada faixa percentual estabelecida em fonte qualificada; o laboratório publica apenas o valor absoluto (/mm3).', 'Sem fonte citável para o percentual: o Fleury, Manual de Exames — Leucograma, sangue total (https://www.fleury.com.br/medicos/exames/leucograma-sangue-total) publica deliberadamente apenas o valor absoluto em /mm3, e a SBPC/ML não fixa tabela nacional. O Indicador absoluto correspondente tem faixa.'),
    ('a2000000-0000-4000-8000-000000000035', (SELECT id FROM health_indicators WHERE code = 'white_cell_morphology'), NULL, NULL, NULL, NULL, NULL, 'Resultado textual (avaliação microscópica do esfregaço sanguíneo). Não há faixa numérica: o resultado esperado em adulto saudável é a ausência de alterações morfológicas dignas de nota na série branca (sem granulações tóxicas, desvio à esquerda significativo, linfócitos atípicos ou blastos). Qualquer achado é descrito em texto livre pelo laboratório.', 'Fleury, Manual de Exames — Leucograma, sangue total (exame inclui avaliação morfológica da série branca), https://www.fleury.com.br/medicos/exames/leucograma-sangue-total'),
    ('a2000000-0000-4000-8000-000000000036', (SELECT id FROM health_indicators WHERE code = 'platelets'), 'M', NULL, NULL, 151000, 304000, 'Contagem de plaquetas, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Plaquetas, contagem, sangue total, https://www.fleury.com.br/medicos/exames/plaquetas-contagem-sangue-total'),
    ('a2000000-0000-4000-8000-000000000037', (SELECT id FROM health_indicators WHERE code = 'platelets'), 'F', NULL, NULL, 163000, 343000, 'Contagem de plaquetas, população adulta brasileira saudável.', 'Fleury, Manual de Exames — Plaquetas, contagem, sangue total, https://www.fleury.com.br/medicos/exames/plaquetas-contagem-sangue-total'),
    ('a2000000-0000-4000-8000-000000000038', (SELECT id FROM health_indicators WHERE code = 'mpv'), NULL, NULL, NULL, 9.2, 12.6, 'Volume plaquetário médio (VPM). A fonte publica um único valor para "ambos os sexos e todas as idades" (adultos), sem distinção por sexo ou faixa etária.', 'Fleury, Manual de Exames — Plaquetas, contagem, sangue total, https://www.fleury.com.br/medicos/exames/plaquetas-contagem-sangue-total'),
    ('a2000000-0000-4000-8000-000000000039', (SELECT id FROM health_indicators WHERE code = 'tsh'), NULL, 20, 59, 0.45, 4.5, 'Faixa de referência para adultos de 20 a 59 anos, segundo o manual laboratorial do Fleury. O limite superior sobe com a idade, e este catálogo traz faixas próprias para 60-69, 70-80 e 81 anos ou mais. Durante a gravidez a faixa muda por trimestre, condição que este sistema não modela em coluna própria. DIVERGÊNCIA REGISTRADA, não semeada: estudos populacionais brasileiros do mesmo grupo (Rosário/Calsolari, Arq Bras Endocrinol Metab 2010 e 2014) encontraram limites superiores mais baixos — cerca de 3,5 mUI/L para 18 a 60 anos (percentis 2,5-97,5 de 0,43 a 3,24) e cerca de 4,6 mUI/L para 70 a 85 anos (0,2 a 4,62) —, parte do debate internacional sobre baixar o corte tradicional. Semeada aqui a faixa do manual laboratorial, que é a impressa nos laudos brasileiros. Não há faixa para 18 e 19 anos: o corte adulto da fonte começa em 20 anos.', 'Fleury Medicina e Saúde — Manual de Exames, "TSH (Hormônio Tiroestimulante)". https://www.fleury.com.br/noticias/tsh-hormonio-tiroestimulante'),
    ('a2000000-0000-4000-8000-000000000040', (SELECT id FROM health_indicators WHERE code = 'tsh'), NULL, 60, 69, 0.44, 6.8, 'Faixa de referência para 60 a 69 anos, mesmo manual. O aumento do limite superior com a idade é fisiológico, mas o quanto ele deve subir é controverso.', 'Fleury Medicina e Saúde — Manual de Exames, "TSH (Hormônio Tiroestimulante)". https://www.fleury.com.br/noticias/tsh-hormonio-tiroestimulante'),
    ('a2000000-0000-4000-8000-000000000041', (SELECT id FROM health_indicators WHERE code = 'tsh'), NULL, 70, 80, 0.44, 7.9, 'Faixa de referência para 70 a 80 anos, mesmo manual.', 'Fleury Medicina e Saúde — Manual de Exames, "TSH (Hormônio Tiroestimulante)". https://www.fleury.com.br/noticias/tsh-hormonio-tiroestimulante'),
    ('a2000000-0000-4000-8000-000000000042', (SELECT id FROM health_indicators WHERE code = 'tsh'), NULL, 81, NULL, 0.48, 10.4, 'Faixa de referência para maiores de 80 anos, mesmo manual.', 'Fleury Medicina e Saúde — Manual de Exames, "TSH (Hormônio Tiroestimulante)". https://www.fleury.com.br/noticias/tsh-hormonio-tiroestimulante'),
    ('a2000000-0000-4000-8000-000000000043', (SELECT id FROM health_indicators WHERE code = 'pth_intact'), NULL, 18, NULL, 15, 65, 'Faixa de um imunoensaio de referência (eletroquimioluminescência, Roche cobas) para 18 anos ou mais. A faixa depende do ensaio/kit usado por cada laboratório — priorize sempre o valor impresso no laudo. PTH só deve ser interpretado junto com cálcio e fósforo séricos e considerando o status de vitamina D do paciente: PTH elevado com cálcio normal costuma refletir deficiência secundária de vitamina D, não hiperparatiroidismo primário; PTH elevado com cálcio também elevado sugere hiperparatiroidismo primário.', 'Mayo Clinic Laboratories — Test ID PTH2, "Parathyroid Hormone, Serum". https://www.mayocliniclabs.com/test-catalog/overview/28379'),
    ('a2000000-0000-4000-8000-000000000044', (SELECT id FROM health_indicators WHERE code = 'vitamin_d_25_hydroxy'), NULL, NULL, NULL, 20, 60, 'DIVERGÊNCIA (posição brasileira): o posicionamento conjunto SBEM/SBPC-ML considera 20–60 ng/mL normal para a população geral saudável (deficiência <20 ng/mL; risco de toxicidade >100 ng/mL, não incluído nesta linha). DIVERGÊNCIAS REGISTRADAS, não semeadas: a mesma fonte SBEM/SBPC-ML recomenda meta mais alta, de 30 a 60 ng/mL, para grupos de risco (idosos, gestantes, lactantes, osteoporose e outras doenças osteometabólicas) — condição clínica que este sistema não modela em coluna própria. A Endocrine Society 2011 usa 30 a 100 ng/mL como suficiência para todos; a própria atualização de 2024 abandonou esses cortes numéricos para a população saudável e passou a recomendar contra a dosagem de rotina.', 'Sociedade Brasileira de Patologia Clínica/Medicina Laboratorial (SBPC/ML) e Sociedade Brasileira de Endocrinologia e Metabologia (SBEM) — Ferreira CES, Moreira CA, Vasconcellos LS. Novo modelo de laudo laboratorial para 25-hidroxivitamina D. J Bras Patol Med Lab. 2020;56(1):1-2. DOI 10.5935/1676-2444.20200052. https://jbpml.org.br/template-for-the-laboratorys-report-of-25-hydroxyvitamin-d-recommendations-form-the-brazilian-society-of-clinical-pathology-laboratory-medicine-sbpc-ml-and-the-brazilian-society-of-endocri/'),
    ('a2000000-0000-4000-8000-000000000045', (SELECT id FROM health_indicators WHERE code = 'vitamin_b12'), NULL, 18, NULL, 180, 914, 'Faixa de referência sérica de laboratório de referência (ensaio imunoenzimático), sem distinção por faixa etária adulta. ng/L é numericamente igual a pg/mL, unidade em que a fonte publica — nenhuma conversão foi necessária. Deficiência: <150 ng/L. A própria fonte trata 150–400 ng/L como zona limítrofe que exige investigação funcional (ácido metilmalônico, homocisteína); outras fontes citam a faixa mais estreita de 200–300 ng/L (≈148–221 pmol/L, usando 1 pg/mL = 0,738 pmol/L) como "deficiência subclínica" discutível, sem consenso sobre tratar ou não nesse intervalo.', 'Mayo Clinic Laboratories — Test ID B12, "Vitamin B12 Assay, Serum". https://www.mayocliniclabs.com/test-catalog/overview/9154/vitamin-b12-assay-serum'),
    ('a2000000-0000-4000-8000-000000000046', (SELECT id FROM health_indicators WHERE code = 'total_cholesterol'), NULL, 20, NULL, NULL, 190, 'Valor referencial desejável: abaixo de 190 mg/dL, tanto em amostra colhida com jejum de 12 h quanto sem jejum (a diretriz vigente não exige jejum para a coleta de rotina do perfil lipídico). A diretriz brasileira atual manteve um valor referencial isolado para o colesterol total — não o abandonou em favor de apenas metas de LDL/não-HDL, ao contrário do que sugerem alguns resumos secundários. Não há piso mínimo estabelecido: colesterol total baixo não é tratado como alteração nesta diretriz.', 'Sociedade Brasileira de Cardiologia (SBC) — Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose 2025, Tabela 3.1 (Arq Bras Cardiol. 2025;122(9):e20250640). https://pmc.ncbi.nlm.nih.gov/articles/PMC12674852/'),
    ('a2000000-0000-4000-8000-000000000047', (SELECT id FROM health_indicators WHERE code = 'hdl_cholesterol'), NULL, 20, NULL, 40, NULL, 'Piso desejável: acima de 40 mg/dL — o mesmo valor é usado com ou sem jejum de 12 h. A diretriz vigente (SBC 2025) NÃO diferencia esse piso por sexo biológico. A diretriz declara explicitamente que "não são propostas metas para o HDL-c": ele é usado como marcador de risco cardiovascular, não como alvo terapêutico, por isso não há teto máximo definido nem meta a perseguir.', 'Sociedade Brasileira de Cardiologia (SBC) — Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose 2025, Tabela 3.1 e seção 5.4 (Arq Bras Cardiol. 2025;122(9):e20250640). https://pmc.ncbi.nlm.nih.gov/articles/PMC12674852/'),
    ('a2000000-0000-4000-8000-000000000048', (SELECT id FROM health_indicators WHERE code = 'ldl_cholesterol'), NULL, 20, NULL, NULL, NULL, 'Sem faixa de normalidade única — DEFINIDA PELO MÉDICO. A diretriz vigente estabelece METAS terapêuticas de LDL-c por categoria de risco cardiovascular, e não uma faixa de normalidade populacional: risco baixo < 115 mg/dL; risco intermediário < 100 mg/dL; risco alto < 70 mg/dL; risco muito alto < 50 mg/dL; risco extremo < 40 mg/dL (mesmos valores com ou sem jejum de 12 h). A estratificação de risco cardiovascular (escores, comorbidades, doença aterosclerótica prévia) é feita pelo médico assistente; o MedLog não tem essa informação, então a meta aplicável a cada usuário deve ser definida na consulta médica, não pelo sistema.', 'Sociedade Brasileira de Cardiologia (SBC) — Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose 2025, Tabela 3.1 e seção 5.2 (Arq Bras Cardiol. 2025;122(9):e20250640). https://pmc.ncbi.nlm.nih.gov/articles/PMC12674852/'),
    ('a2000000-0000-4000-8000-000000000049', (SELECT id FROM health_indicators WHERE code = 'non_hdl_cholesterol'), NULL, 20, NULL, NULL, NULL, 'Sem faixa de normalidade única — DEFINIDA PELO MÉDICO. Assim como o LDL-c, o não-HDL-c tem meta terapêutica coprimária por categoria de risco cardiovascular, não uma faixa de normalidade: risco baixo < 145 mg/dL; risco intermediário < 130 mg/dL; risco alto < 100 mg/dL; risco muito alto < 80 mg/dL; risco extremo < 70 mg/dL (mesmos valores com ou sem jejum de 12 h). É particularmente útil quando os triglicérides estão acima de 150 mg/dL. A meta aplicável depende do risco cardiovascular, definido pelo médico.', 'Sociedade Brasileira de Cardiologia (SBC) — Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose 2025, Tabela 3.1 e seção 5.2 (Arq Bras Cardiol. 2025;122(9):e20250640). https://pmc.ncbi.nlm.nih.gov/articles/PMC12674852/'),
    ('a2000000-0000-4000-8000-000000000050', (SELECT id FROM health_indicators WHERE code = 'vldl_cholesterol'), NULL, NULL, NULL, NULL, 30, 'Valor referencial: abaixo de 30 mg/dL. O VLDL-colesterol não é medido diretamente na rotina, nem consta na diretriz brasileira de dislipidemias vigente (SBC 2025) como parâmetro com faixa ou meta própria — é habitualmente estimado por cálculo (Triglicérides ÷ 5, válido apenas com TG < 400 mg/dL), a partir da mesma amostra de jejum usada para os triglicérides. Faixa adotada de manual laboratorial de referência internacional por ausência de faixa isolada nas diretrizes médicas brasileiras/internacionais consultadas.', 'Mayo Clinic Laboratories — Lipoprotein Metabolism Profile, Serum (Test ID: LMPP). https://www.mayocliniclabs.com/test-catalog/overview/83673/lipoprotein-metabolism-profile-serum'),
    ('a2000000-0000-4000-8000-000000000051', (SELECT id FROM health_indicators WHERE code = 'triglycerides'), NULL, 20, NULL, NULL, 150, 'Valor desejável EM JEJUM de 12 h: abaixo de 150 mg/dL — é o valor usado nesta linha (é o que consta no laudo de rotina, colhido em jejum). SEM jejum, o valor desejável equivalente é abaixo de 175 mg/dL (diferente do valor em jejum; a diretriz aceita a coleta sem jejum para avaliação inicial, mas recomenda nova coleta em jejum de 12 h se o TG sem jejum for ≥ 440 mg/dL). Hipertrigliceridemia grave, com risco de pancreatite aguda, é definida a partir de 500 mg/dL. Sem piso mínimo definido.', 'Sociedade Brasileira de Cardiologia (SBC) — Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose 2025, Tabela 3.1 e seção 5.5 (Arq Bras Cardiol. 2025;122(9):e20250640). https://pmc.ncbi.nlm.nih.gov/articles/PMC12674852/'),
    ('a2000000-0000-4000-8000-000000000052', (SELECT id FROM health_indicators WHERE code = 'psa_total'), 'M', NULL, 39, NULL, 2.0, 'Faixa de referência por década de idade (não é "faixa de normalidade" no sentido clássico: PSA cresce fisiologicamente com a idade e com o volume prostático). Aplica-se apenas a quem tem próstata. Não semeado, por não ser faixa de normalidade: o corte clássico de rastreamento de 4,0 ng/mL, que a Sociedade Brasileira de Urologia deliberadamente não adota como valor normal universal — a nota oficial da SBU de 2018 fala em decisão individualizada e compartilhada a partir dos 50 anos, ou 45 para negros e para quem tem parente de primeiro grau com câncer de próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Diagnostic, Serum — https://www.mayocliniclabs.com/test-catalog/overview/9284/prostate-specific-antigen-psa-diagnostic-serum'),
    ('a2000000-0000-4000-8000-000000000053', (SELECT id FROM health_indicators WHERE code = 'psa_total'), 'M', 40, 49, NULL, 2.5, 'Faixa de referência por década de idade, mesmo esquema do Mayo Clinic Laboratories (baseado em Oesterling et al., amplamente adotado por laboratórios). Aplica-se apenas a quem tem próstata. Não semeado, por não ser faixa de normalidade: o corte clássico de rastreamento de 4,0 ng/mL, que a Sociedade Brasileira de Urologia deliberadamente não adota como valor normal universal — a nota oficial da SBU de 2018 fala em decisão individualizada e compartilhada a partir dos 50 anos, ou 45 para negros e para quem tem parente de primeiro grau com câncer de próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Diagnostic, Serum — https://www.mayocliniclabs.com/test-catalog/overview/9284/prostate-specific-antigen-psa-diagnostic-serum'),
    ('a2000000-0000-4000-8000-000000000054', (SELECT id FROM health_indicators WHERE code = 'psa_total'), 'M', 50, 59, NULL, 3.5, 'Faixa de referência por década de idade. Aplica-se apenas a quem tem próstata. Não semeado, por não ser faixa de normalidade: o corte clássico de rastreamento de 4,0 ng/mL, que a Sociedade Brasileira de Urologia deliberadamente não adota como valor normal universal — a nota oficial da SBU de 2018 fala em decisão individualizada e compartilhada a partir dos 50 anos, ou 45 para negros e para quem tem parente de primeiro grau com câncer de próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Diagnostic, Serum — https://www.mayocliniclabs.com/test-catalog/overview/9284/prostate-specific-antigen-psa-diagnostic-serum'),
    ('a2000000-0000-4000-8000-000000000055', (SELECT id FROM health_indicators WHERE code = 'psa_total'), 'M', 60, 69, NULL, 4.5, 'Faixa de referência por década de idade. Aplica-se apenas a quem tem próstata. Não semeado, por não ser faixa de normalidade: o corte clássico de rastreamento de 4,0 ng/mL, que a Sociedade Brasileira de Urologia deliberadamente não adota como valor normal universal — a nota oficial da SBU de 2018 fala em decisão individualizada e compartilhada a partir dos 50 anos, ou 45 para negros e para quem tem parente de primeiro grau com câncer de próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Diagnostic, Serum — https://www.mayocliniclabs.com/test-catalog/overview/9284/prostate-specific-antigen-psa-diagnostic-serum'),
    ('a2000000-0000-4000-8000-000000000056', (SELECT id FROM health_indicators WHERE code = 'psa_total'), 'M', 70, 79, NULL, 6.5, 'Faixa de referência por década de idade. Aplica-se apenas a quem tem próstata. Não semeado, por não ser faixa de normalidade: o corte clássico de rastreamento de 4,0 ng/mL, que a Sociedade Brasileira de Urologia deliberadamente não adota como valor normal universal — a nota oficial da SBU de 2018 fala em decisão individualizada e compartilhada a partir dos 50 anos, ou 45 para negros e para quem tem parente de primeiro grau com câncer de próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Diagnostic, Serum — https://www.mayocliniclabs.com/test-catalog/overview/9284/prostate-specific-antigen-psa-diagnostic-serum'),
    ('a2000000-0000-4000-8000-000000000057', (SELECT id FROM health_indicators WHERE code = 'psa_total'), 'M', 80, NULL, NULL, 7.2, 'Faixa de referência por década de idade, faixa mais alta (≥80 anos). Aplica-se apenas a quem tem próstata. Não semeado, por não ser faixa de normalidade: o corte clássico de rastreamento de 4,0 ng/mL, que a Sociedade Brasileira de Urologia deliberadamente não adota como valor normal universal — a nota oficial da SBU de 2018 fala em decisão individualizada e compartilhada a partir dos 50 anos, ou 45 para negros e para quem tem parente de primeiro grau com câncer de próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Diagnostic, Serum — https://www.mayocliniclabs.com/test-catalog/overview/9284/prostate-specific-antigen-psa-diagnostic-serum'),
    ('a2000000-0000-4000-8000-000000000058', (SELECT id FROM health_indicators WHERE code = 'psa_free'), 'M', NULL, NULL, NULL, NULL, 'Não há faixa de normalidade isolada estabelecida para o PSA livre em valor absoluto: o valor só tem significado clínico quando expresso como razão PSA livre/PSA total (ver o Indicador "Relação PSA livre/PSA total"). Aplica-se apenas a quem tem próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Free and Total, Serum — https://www.mayocliniclabs.com/test-catalog/download-setup?format=pdf&unit_code=81944'),
    ('a2000000-0000-4000-8000-000000000059', (SELECT id FROM health_indicators WHERE code = 'psa_free_total_ratio'), 'M', NULL, NULL, NULL, NULL, 'Não é uma faixa de normalidade universal: a razão PSA livre/PSA total só é usada para estratificar risco quando o PSA total está na "zona cinzenta" de 4,0–10,0 ng/mL e o toque retal não é suspeito. Nessa faixa, razão > 25% associa-se a menor probabilidade de câncer na biópsia (9–16% conforme a idade) e razão ≤ 10% a maior probabilidade (49–65% conforme a idade); fora da zona cinzenta (PSA total < 2,0 ou > 10,0 ng/mL) a razão agrega pouca informação. Aplica-se apenas a quem tem próstata.', 'Mayo Clinic Laboratories, Prostate-Specific Antigen (PSA), Free and Total, Serum — https://www.mayocliniclabs.com/test-catalog/download-setup?format=pdf&unit_code=81944'),
    ('a2000000-0000-4000-8000-000000000060', (SELECT id FROM health_indicators WHERE code = 'cea'), NULL, NULL, NULL, NULL, NULL, 'Marcador tumoral: não existe faixa de normalidade estabelecida para uso em rastreamento da população geral. Não é diagnóstico e não deve ser interpretado como valor isolado — a informação clinicamente relevante é a tendência de variação em dosagens seriadas do mesmo paciente, preferencialmente no mesmo laboratório e método, para acompanhar doença já diagnosticada ou resposta a tratamento. Limite superior de referência do ensaio, que NÃO é faixa de normalidade e por isso não foi semeado em min/max: 3,0 microgramas/L em não fumantes (Mayo Clinic Laboratories, corroborado pelo Fleury), subindo para cerca de 5,0 em fumantes. Tabagismo não é coluna neste sistema.', 'Mayo Clinic Laboratories, Carcinoembryonic Antigen (CEA), Serum — https://www.mayocliniclabs.com/test-catalog/overview/8521/carcinoembryonic-antigen-cea-serum'),
    ('a2000000-0000-4000-8000-000000000061', (SELECT id FROM health_indicators WHERE code = 'ca_19_9'), NULL, NULL, NULL, NULL, NULL, 'Marcador tumoral: não existe faixa de normalidade estabelecida para uso em rastreamento da população geral. Usado principalmente para acompanhar resposta a tratamento e recidiva em neoplasias gastrointestinais conhecidas (especialmente pâncreas e vias biliares); a tendência ao longo do tempo é mais informativa que o valor isolado. Cerca de 5–7% da população é "Lewis-antígeno negativa" e não produz CA 19-9 mesmo com câncer presente, tornando o exame não informativo nesses casos. Limites superiores de referência de ensaio, que NÃO são faixa de normalidade e por isso não foram semeados em min/max: 35 U/mL pela Mayo Clinic Laboratories e 37 U/mL pelos laboratórios brasileiros que usam o mesmo método (Hermes Pardini e correlatos). DIVERGÊNCIA de calibrador/kit, não de fonte: vale sempre o valor impresso no laudo.', 'Mayo Clinic Laboratories, Carbohydrate Antigen 19-9 (CA 19-9), Serum — https://www.mayocliniclabs.com/test-catalog/overview/9288'),
    ('a2000000-0000-4000-8000-000000000062', (SELECT id FROM health_indicators WHERE code = 'amylase'), NULL, NULL, NULL, 28, 100, 'Faixa de referência laboratorial usual para amilase sérica total em adultos; depende do método/kit e do equipamento do laboratório — o valor impresso no laudo específico prevalece sobre esta tabela.', 'Mayo Clinic Laboratories, Amylase, Serum — https://www.mayocliniclabs.com/test-catalog/overview/8352; faixa idêntica (28–100 U/L) corroborada por laboratórios brasileiros do grupo Fleury (a+ Medicina Diagnóstica) — https://www.fleury.com.br/exames/amilase-soro'),
    ('a2000000-0000-4000-8000-000000000063', (SELECT id FROM health_indicators WHERE code = 'lipase'), NULL, NULL, NULL, 13, 60, 'Faixa de referência laboratorial usual para lipase sérica em adultos; depende do método/kit e do equipamento do laboratório — o valor impresso no laudo específico prevalece sobre esta tabela. O limite superior (60 U/L) é consistente com o valor publicado pelo Fleury.', 'Mayo Clinic Laboratories, Lipase, Serum — https://www.mayocliniclabs.com/test-catalog/overview/8328; limite superior corroborado por Fleury Medicina e Saúde, Lipase, soro — https://www.fleury.com.br/exames/lipase-soro'),
    ('a2000000-0000-4000-8000-000000000064', (SELECT id FROM health_indicators WHERE code = 'urea_serum'), 'M', NULL, NULL, 17.1, 51.4, 'Convertido a partir do nitrogênio ureico (BUN), que é o que a fonte mede: BUN 8–24 mg/dL × 2,14 = ureia 17,1–51,4 mg/dL. Válido para homens ≥18 anos.', 'Mayo Clinic Laboratories — Blood Urea Nitrogen (BUN), Serum — https://www.mayocliniclabs.com/test-catalog/overview/81793/blood-urea-nitrogen-bun-serum'),
    ('a2000000-0000-4000-8000-000000000065', (SELECT id FROM health_indicators WHERE code = 'urea_serum'), 'F', NULL, NULL, 12.8, 44.9, 'Convertido a partir do nitrogênio ureico (BUN): BUN 6–21 mg/dL × 2,14 = ureia 12,8–44,9 mg/dL. Válido para mulheres ≥18 anos.', 'Mayo Clinic Laboratories — Blood Urea Nitrogen (BUN), Serum — https://www.mayocliniclabs.com/test-catalog/overview/81793/blood-urea-nitrogen-bun-serum'),
    ('a2000000-0000-4000-8000-000000000066', (SELECT id FROM health_indicators WHERE code = 'creatinine_serum'), 'M', NULL, NULL, 0.74, 1.35, 'Faixa adulta (fonte reporta a partir de 15 anos; o MedLog só cadastra adultos).', 'Mayo Clinic Laboratories — Creatinine with eGFR, Serum — https://www.mayocliniclabs.com/test-catalog/overview/48216/creatinine-with-estimated-glomerular-filtration-rate-egfr-serum'),
    ('a2000000-0000-4000-8000-000000000067', (SELECT id FROM health_indicators WHERE code = 'creatinine_serum'), 'F', NULL, NULL, 0.59, 1.04, 'Faixa adulta (fonte reporta a partir de 16 anos; o MedLog só cadastra adultos).', 'Mayo Clinic Laboratories — Creatinine with eGFR, Serum — https://www.mayocliniclabs.com/test-catalog/overview/48216/creatinine-with-estimated-glomerular-filtration-rate-egfr-serum'),
    ('a2000000-0000-4000-8000-000000000068', (SELECT id FROM health_indicators WHERE code = 'egfr_ckd_epi_2009_black'), NULL, NULL, NULL, 60, NULL, 'Estimada pela equação CKD-EPI 2009 na variante que mantém o coeficiente racial (multiplica o resultado por 1,159 quando o paciente é afrodescendente — fórmula publicada no posicionamento SBN/SBPC/ML). Estratificação KDIGO das categorias de TFG: G1 ≥90 (normal ou alta), G2 60–89 (levemente diminuída), G3a 45–59 (leve a moderadamente diminuída), G3b 30–44 (moderada a severamente diminuída), G4 15–29 (severamente diminuída), G5 <15 (falência renal). Na ausência de outro marcador de lesão renal (ex.: albuminúria), G1 e G2 isoladas NÃO configuram doença renal crônica. O corte prático usado nesta faixa (min=60) é o limiar clínico: TFG <60 mL/min/1,73 m2 sustentada por mais de 3 meses já define doença renal crônica pelo KDIGO/SBN, mesmo que G1 estrito exija ≥90 para "normal". A fórmula já embute idade e sexo nos seus coeficientes, então esta faixa não é condicionada por idade/sexo. Existem 5 Indicadores para a mesma grandeza porque as equações diferem: a CKD-EPI 2009 e a MDRD mantinham coeficiente de raça (por isso têm variante "afrodescendente"/"não afrodescendente"); a CKD-EPI 2021 removeu esse coeficiente deliberadamente e por isso é uma fórmula única, sem variantes.', 'KDIGO — Clinical Practice Guideline for CKD Evaluation and Management (categorias G1–G5) — https://kdigo.org/guidelines/ckd-evaluation-and-management/ ; SBN/SBPC-ML — Posicionamento consensual sobre estimativa da TFG — Braz J Nephrol 2024;46(3):e20230193 — https://www.scielo.br/j/jbn/a/s8GPHkHPbCKLTk8GBqWdzTK/?lang=pt'),
    ('a2000000-0000-4000-8000-000000000069', (SELECT id FROM health_indicators WHERE code = 'egfr_ckd_epi_2009_non_black'), NULL, NULL, NULL, 60, NULL, 'Estimada pela equação CKD-EPI 2009 na variante sem o coeficiente racial (paciente não afrodescendente). Mesma estratificação KDIGO da variante afrodescendente: G1 ≥90 (normal ou alta), G2 60–89 (levemente diminuída, sem configurar DRC isoladamente), G3a 45–59, G3b 30–44, G4 15–29, G5 <15 (falência renal). Corte prático de normalidade adotado aqui: 60 mL/min/1,73 m2 (definição de DRC do KDIGO/SBN quando sustentada por >3 meses). A fórmula já embute idade e sexo, portanto esta faixa não é condicionada por idade/sexo.', 'KDIGO — Clinical Practice Guideline for CKD Evaluation and Management — https://kdigo.org/guidelines/ckd-evaluation-and-management/ ; SBN/SBPC-ML — Posicionamento consensual sobre estimativa da TFG — https://www.scielo.br/j/jbn/a/s8GPHkHPbCKLTk8GBqWdzTK/?lang=pt'),
    ('a2000000-0000-4000-8000-000000000070', (SELECT id FROM health_indicators WHERE code = 'egfr_ckd_epi_2021'), NULL, NULL, NULL, 60, NULL, 'Estimada pela equação CKD-EPI 2021, que usa apenas creatinina sérica, idade e sexo e removeu deliberadamente o coeficiente de raça presente nas equações anteriores (CKD-EPI 2009 e MDRD) — por isso é uma fórmula única, sem variantes "afrodescendente"/"não afrodescendente". Adotada pela SBN/SBPC/ML e pela National Kidney Foundation/American Society of Nephrology (NKF-ASN) como padrão atual. Mesma estratificação KDIGO: G1 ≥90 (normal ou alta), G2 60–89 (levemente diminuída, sem configurar DRC isoladamente), G3a 45–59, G3b 30–44, G4 15–29, G5 <15 (falência renal). Corte prático de normalidade adotado: 60 mL/min/1,73 m2. A fórmula já embute idade e sexo, portanto esta faixa não é condicionada por idade/sexo.', 'KDIGO — Clinical Practice Guideline for CKD Evaluation and Management — https://kdigo.org/guidelines/ckd-evaluation-and-management/ ; SBN/SBPC-ML — Posicionamento consensual sobre estimativa da TFG — https://www.scielo.br/j/jbn/a/s8GPHkHPbCKLTk8GBqWdzTK/?lang=pt ; Inker LA et al., New Creatinine- and Cystatin C-Based Equations to Estimate GFR without Race, N Engl J Med 2021 — https://pubmed.ncbi.nlm.nih.gov/34554658/'),
    ('a2000000-0000-4000-8000-000000000071', (SELECT id FROM health_indicators WHERE code = 'egfr_mdrd_black'), NULL, NULL, NULL, 60, NULL, 'Estimada pela equação MDRD (4 variáveis) na variante que mantém o coeficiente racial (multiplica por 1,212 quando o paciente é afrodescendente). Equação hoje considerada obsoleta pela SBN/SBPC-ML e substituída por CKD-EPI, mas mantida aqui por já existir como Indicador legado no MedLog. Mesma estratificação KDIGO: G1 ≥90 (normal ou alta), G2 60–89 (levemente diminuída), G3a 45–59, G3b 30–44, G4 15–29, G5 <15 (falência renal). Corte prático de normalidade adotado: 60 mL/min/1,73 m2. A fórmula já embute idade e sexo, portanto esta faixa não é condicionada por idade/sexo.', 'KDIGO — Clinical Practice Guideline for CKD Evaluation and Management — https://kdigo.org/guidelines/ckd-evaluation-and-management/ ; SBN/SBPC-ML — Posicionamento consensual sobre estimativa da TFG (fórmula e coeficiente de raça do MDRD) — https://www.scielo.br/j/jbn/a/s8GPHkHPbCKLTk8GBqWdzTK/?lang=pt'),
    ('a2000000-0000-4000-8000-000000000072', (SELECT id FROM health_indicators WHERE code = 'egfr_mdrd_non_black'), NULL, NULL, NULL, 60, NULL, 'Estimada pela equação MDRD (4 variáveis) na variante sem o coeficiente racial (paciente não afrodescendente). Mesma ressalva de obsolescência da variante afrodescendente. Mesma estratificação KDIGO: G1 ≥90 (normal ou alta), G2 60–89 (levemente diminuída), G3a 45–59, G3b 30–44, G4 15–29, G5 <15 (falência renal). Corte prático de normalidade adotado: 60 mL/min/1,73 m2. A fórmula já embute idade e sexo, portanto esta faixa não é condicionada por idade/sexo.', 'KDIGO — Clinical Practice Guideline for CKD Evaluation and Management — https://kdigo.org/guidelines/ckd-evaluation-and-management/ ; SBN/SBPC-ML — Posicionamento consensual sobre estimativa da TFG — https://www.scielo.br/j/jbn/a/s8GPHkHPbCKLTk8GBqWdzTK/?lang=pt'),
    ('a2000000-0000-4000-8000-000000000073', (SELECT id FROM health_indicators WHERE code = 'uric_acid_serum'), 'M', NULL, NULL, 3.7, 8.0, 'Faixa adulta (fonte reporta a partir de 16 anos; o MedLog só cadastra adultos).', 'Mayo Clinic Laboratories — Uric Acid, Serum — https://www.mayocliniclabs.com/test-catalog/overview/8440/uric-acid-serum'),
    ('a2000000-0000-4000-8000-000000000074', (SELECT id FROM health_indicators WHERE code = 'uric_acid_serum'), 'F', NULL, NULL, 2.7, 6.1, 'Faixa adulta (fonte reporta a partir de 13 anos; o MedLog só cadastra adultos).', 'Mayo Clinic Laboratories — Uric Acid, Serum — https://www.mayocliniclabs.com/test-catalog/overview/8440/uric-acid-serum'),
    ('a2000000-0000-4000-8000-000000000075', (SELECT id FROM health_indicators WHERE code = 'sodium_serum'), NULL, NULL, NULL, 135, 145, 'Não difere por sexo biológico nesta fonte. A fonte publica em mmol/L; para o sódio (íon monovalente), 1 mmol/L equivale numericamente a 1 mEq/L, então o valor foi apenas re-rotulado, sem conversão aritmética.', 'Mayo Clinic Laboratories — Sodium, Serum — https://www.mayocliniclabs.com/test-catalog/overview/602353/sodium-serum'),
    ('a2000000-0000-4000-8000-000000000076', (SELECT id FROM health_indicators WHERE code = 'potassium_serum'), NULL, NULL, NULL, 3.6, 5.2, 'Não difere por sexo biológico nesta fonte. A fonte publica em mmol/L; para o potássio (íon monovalente), 1 mmol/L equivale numericamente a 1 mEq/L, então o valor foi apenas re-rotulado, sem conversão aritmética.', 'Mayo Clinic Laboratories — Potassium, Serum — https://www.mayocliniclabs.com/test-catalog/overview/602352'),
    ('a2000000-0000-4000-8000-000000000077', (SELECT id FROM health_indicators WHERE code = 'calcium_serum'), NULL, 18, 59, 8.6, 10.0, 'Cálcio total (não iônico), já na unidade canônica mg/dL — sem conversão. Não difere por sexo biológico nesta fonte.', 'Mayo Clinic Laboratories — Calcium, Total, Serum — https://www.mayocliniclabs.com/test-catalog/overview/601514'),
    ('a2000000-0000-4000-8000-000000000078', (SELECT id FROM health_indicators WHERE code = 'calcium_serum'), NULL, 60, NULL, 8.8, 10.2, 'Cálcio total (não iônico), já na unidade canônica mg/dL — sem conversão. Faixa própria para ≥60 anos, ligeiramente mais alta que a de adultos mais jovens. Não difere por sexo biológico nesta fonte.', 'Mayo Clinic Laboratories — Calcium, Total, Serum — https://www.mayocliniclabs.com/test-catalog/overview/601514');

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM indicator_normal_ranges WHERE id LIKE 'a2000000-0000-4000-8000-%';
-- +goose StatementEnd
